# Generated by Django 5.2.7 on 2025-11-12 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_product_is_active'),
        ('sales', '0003_alter_orderitem_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, help_text='Número único de ticket generado automáticamente', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Título breve del reclamo', max_length=255)),
                ('description', models.TextField(help_text='Descripción detallada del problema')),
                ('damage_type', models.CharField(choices=[('FACTORY_DEFECT', 'Defecto de Fábrica'), ('SHIPPING_DAMAGE', 'Daño en Envío'), ('WRONG_PRODUCT', 'Producto Incorrecto'), ('MISSING_PARTS', 'Piezas Faltantes'), ('NOT_AS_DESCRIBED', 'No Coincide con Descripción'), ('OTHER', 'Otro')], default='OTHER', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_REVIEW', 'En Revisión'), ('REQUIRES_INFO', 'Requiere Información'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('RESOLVED', 'Resuelto'), ('CLOSED', 'Cerrado')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=20)),
                ('resolution_type', models.CharField(blank=True, choices=[('FULL_REFUND', 'Reembolso Total'), ('PARTIAL_REFUND', 'Reembolso Parcial'), ('REPLACEMENT', 'Reemplazo del Producto'), ('REPAIR', 'Reparación'), ('NONE', 'Sin Resolución')], default='NONE', max_length=50)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notas sobre la resolución del reclamo', null=True)),
                ('admin_response', models.TextField(blank=True, help_text='Respuesta del administrador al cliente', null=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Notas internas (no visibles para el cliente)', null=True)),
                ('customer_rating', models.PositiveIntegerField(blank=True, help_text='Calificación del cliente sobre la resolución (1-5)', null=True)),
                ('customer_feedback', models.TextField(blank=True, help_text='Comentarios del cliente sobre la resolución', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Fecha en que se resolvió el reclamo', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='Fecha en que se cerró el reclamo', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Administrador asignado al reclamo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_claims', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Cliente que realiza el reclamo', on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(help_text='Orden asociada al reclamo', on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='sales.order')),
                ('order_item', models.ForeignKey(blank=True, help_text='Item específico de la orden', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='sales.orderitem')),
                ('product', models.ForeignKey(help_text='Producto sobre el que se reclama', on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='products.product')),
            ],
            options={
                'verbose_name': 'Reclamo',
                'verbose_name_plural': 'Reclamos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Descripción de la acción realizada', max_length=255)),
                ('old_status', models.CharField(blank=True, choices=[('PENDING', 'Pendiente'), ('IN_REVIEW', 'En Revisión'), ('REQUIRES_INFO', 'Requiere Información'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('RESOLVED', 'Resuelto'), ('CLOSED', 'Cerrado')], max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, choices=[('PENDING', 'Pendiente'), ('IN_REVIEW', 'En Revisión'), ('REQUIRES_INFO', 'Requiere Información'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('RESOLVED', 'Resuelto'), ('CLOSED', 'Cerrado')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el cambio', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='claims.claim')),
                ('user', models.ForeignKey(help_text='Usuario que realizó el cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Reclamo',
                'verbose_name_plural': 'Historial de Reclamos',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ClaimImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Imagen de evidencia del daño', upload_to='claims/%Y/%m/%d/')),
                ('description', models.CharField(blank=True, help_text='Descripción de la imagen', max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='claims.claim')),
            ],
            options={
                'verbose_name': 'Imagen de Reclamo',
                'verbose_name_plural': 'Imágenes de Reclamos',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status', 'created_at'], name='claims_clai_status_58edc3_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['customer', 'status'], name='claims_clai_custome_343149_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['ticket_number'], name='claims_clai_ticket__8078dc_idx'),
        ),
    ]
