# Generated by Django 5.2.7 on 2025-11-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SALE_CREATED', 'Venta Creada'), ('SALE_UPDATED', 'Venta Actualizada'), ('SALE_DELETED', 'Venta Eliminada'), ('PRODUCT_LOW_STOCK', 'Stock Bajo'), ('PRODUCT_CREATED', 'Producto Creado'), ('REPORT_GENERATED', 'Reporte Generado'), ('ML_PREDICTION', 'Predicción ML'), ('CLAIM_CREATED', 'Reclamo Creado'), ('CLAIM_UPDATED', 'Reclamo Actualizado'), ('CLAIM_ASSIGNED', 'Reclamo Asignado'), ('CLAIM_RESOLVED', 'Reclamo Resuelto'), ('SYSTEM', 'Sistema'), ('CUSTOM', 'Personalizado')], default='CUSTOM', max_length=50),
        ),
    ]
