# Generated by Django 5.2.6 on 2025-11-10 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Archivo de imagen', upload_to='products/')),
                ('order', models.IntegerField(default=0, help_text='Orden de visualización (menor número = primera)')),
                ('is_primary', models.BooleanField(default=False, help_text='Marca esta imagen como la principal (solo una por producto)')),
                ('alt_text', models.CharField(blank=True, help_text='Texto alternativo para accesibilidad', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='Producto al que pertenece la imagen', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
                'db_table': 'product_images',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['product', 'order'], name='product_ima_product_93d64d_idx'), models.Index(fields=['product', 'is_primary'], name='product_ima_product_c8c86a_idx')],
            },
        ),
    ]
