# Generated by Django 5.2.6 on 2025-11-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desmarcar para ocultar el producto sin eliminarlo. Protege el historial de ventas.'),
        ),
    ]
