# Generated by Django 5.2.7 on 2025-11-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='cloudinary_url',
            field=models.URLField(blank=True, help_text='URL de Cloudinary (se genera automáticamente en producción)', max_length=500, null=True),
        ),
    ]
